#!/usr/bin/bash


import sys
import time
import math


def pollard_rho(n):
    if (n % 2 == 0):
        return (2)
    x = 2
    y = 2
    d = 1

    f = lambda x: (x**2 + 1) % n
    while (d == 1):
        x = f(x)
        y = f(f(y))
        d = math.gcd(abs(x - y), n)
    return (d)


def main():

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    input_file = sys.argv[1]
    start_time = time.time()

    try:
        with open(input_file, "r") as file:
            num = file.readlines()
    for line in file:
        numb = int(line.strip())
        factor = pollard_rho(num)

        if (factor == num):
            print(f"{num} is prime.")
        else:
            print(f"{num}={factor}*{num // factor}")

        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()
    except FileNotFoundError:
        print(f"File not Found: {input_file}")
        sys.exit(1)


if __name__ == '__main__':
    main()
